### ISSUE TITLE
Append Git commit to ISO and zsync file names

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/iso-tool#16]
It would be helpful to keep track of the commit creating the ISO and the zsync file.

**Comment by lslvr** [comment]
You are right about it. But, for that purpose, we need to create statically named symlinks on the server, that point to the newest files (the ISO image and the zsync file).

**Comment by UriHerrera** [comment]
cc @lnxslck

**Comment by lslvr** [comment]
We could, rather, write the commit on a file in the ISO. It could be easier to manage the updates in that way.

**Comment by UriHerrera** [comment]
How would it look like?

**Comment by lslvr** [comment]
Something like `/.git-commit`. The content of that file should contain the commit hash that created that specific ISO.

**Comment by UriHerrera** [comment]
I think Travis does create  ISO files that have the git commit, right @lnxslck

**Comment by lslvr** [comment]
Do the symlinks work?

**Comment by UriHerrera** [comment]
It creates files named like this ` IMAGE-d665758.iso` so we can symlink `nitrux_release_stable` or development to the latest image generated by Travis.

**Comment by lslvr** [comment]
Exactly. If that works well already, then this is done.

**Comment by lslvr** [comment]
It would be better to use a standard name for the images generated by the branches, and to write the commit hash somewhere in the image. In that way, we will not be creating lots of files with different names in our server. Uploading files to it would overwrite the old ones, which would be the ideal way of operation.

**Comment by lslvr** [comment]
This is already solved.
