### ISSUE TITLE
Append file extension to ISO image and zsync file

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/iso-tool#17]
Currently, the script is generating two files
- `nitrux_release_testing.iso` and,
- `nitrux_release_testing.iso.zsync`

The same name is given to both files and this is because of the value of `IMAGE_NAME=`
https://github.com/Nitrux/mkiso/blob/a39feb982df98847978d15840f02c2bfeda1b820/build.sh#L9

It seems that the file extension is only added to the zsync file but not the ISO image.
https://github.com/Nitrux/mkiso/blob/a39feb982df98847978d15840f02c2bfeda1b820/build.sh#L96-L107
https://github.com/Nitrux/mkiso/blob/a39feb982df98847978d15840f02c2bfeda1b820/build.sh#L112

**Comment by lslvr** [comment]
What would this be for? As of now, it doesn't matter how the files are named, as long as the URL to the `zsync` file is written to the ISO image (for being processed properly by `znx`).

**Comment by UriHerrera** [comment]
Product naming.  The ISO should be `nitrux_release_testing.iso` and the zsync file should be `nitrux_release_testing.zsync`.
