### ISSUE TITLE
Add AppImageUpdate to ISO

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/iso-tool#21]
Provide an alternative way to update deployed AppImages.

https://github.com/AppImage/AppImageUpdate

Add Dolphin service menu file to `/usr/share/kservices5/ServiceMenus/` for system-wide availability.

https://github.com/AppImage/AppImageKit/issues/169#issuecomment-246059924

**Comment by probonopd** [comment]
Don't forget to make AppImages updateable by right-clicking. https://www.youtube.com/watch?v=RlymaRpTSqk
