### ISSUE TITLE
Drop dash as the default /bin/sh and use mksh

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/iso-tool#26]
Ubuntu's default shell is Dash. Dash doesn't meet our requirements for a POSIX shell, and since there are better shells out there like [MirBSD Korn Shell Source Code Mirror](https://github.com/MirBSD/mksh), let's use it instead.

**Comment by 0xEAX** [comment]
Why specifically `mksh`? [According](https://unix.stackexchange.com/a/148098) [to](https://unix.stackexchange.com/a/206732) some basic searching I did after seeing your bounty, it looks like Dash is going to be faster, so why not just use Dash?

**Comment by lslvr** [comment]
`dash` is not meant for interactive use. OTOH, `bash` is full of bugs. `mksh` is very stable, compliant with POSIX (2) and very good for interactive use.

**Comment by 0xEAX** [comment]
Alright, good enough reasoning for me. Thanks for the response.

**Comment by UriHerrera** [comment]
This commit https://github.com/Nitrux/nitrux-iso-tool/commit/f9819f371f54e42d1a0d4aaf1a5db8e859599a7c adds `mksh` as the default shell.
