### ISSUE TITLE
Implement znx INFO file

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/iso-tool#31]
znx will make use of a `.INFO` file for updates. The code here only embeds the update URL in the ISO.

https://github.com/Nitrux/znx/issues/40

**Comment by lslvr** [comment]
:thinking: I remember to have written the necessary code to write the `.INFO` file.

**Comment by UriHerrera** [comment]
Yeah, I remember that too, but I couldn't find it.

**Comment by lslvr** [comment]
Implemented on 782be05.
