### ISSUE TITLE
Wrong URL in update information?

### ISSUE THREAD

**Issue by probonopd** [Nitrux/iso-tool#37]
```
me@host:~$ dd if=/isodevice/boot/iso/nitrux_release_testing.iso  bs=1 skip=33651 count=512 2>/dev/null
http://88.198.66.58:8000/nitrux_release_testing.iso.zsync
```

but

http://88.198.66.58:8000/nitrux_release_testing.iso.zsync

does not seem to exist... (my `nitrux_release_testing.iso` is from October 2018)

**Comment by UriHerrera** [comment]
> What does me@host:~$ dd if=/isodevice/boot/iso/nitrux_release_testing.iso bs=1 skip=33651 count=512 2>/dev/null give on the latest Nitrux version? (Don't have one at hand)

@probono This is the output of the command, it points to the `.zsync` file with the update information.

`zsync|http://repo.nxos.org:8000/nitrux-development-amd64.zsync `

As @luis-lavaire pointed out, `nitrux_release_testing.iso` doesn't exist anymore. 

The existing ISOs are:

```
nitrux-stable-amd64.iso
nitrux-development-amd64.iso
test_build_devuan-znx
test_build_elementary-znx
```

The last two don't have the `.iso` file extension but they are ISO 9660 bootable images.

**Comment by probonopd** [comment]
Thanks for the clarification.
