### ISSUE TITLE
Reduce the boot time of Nitrux

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/iso-tool#41]
As commented in Nitrux/nitrux-bug-tracker#220 the boot time is currently *over* 30 seconds (it's almost 50 in fact), and that's not acceptable.

We have to investigate why it takes the operating system so much time to boot.

**Comment by UriHerrera** [comment]
I've tried to reduce the boot time by disabling some services using `systctl.` However, while it does reduce the boot time, it's only a marginal gain, for instance, it was taking 43 seconds to get from the GRUB entry of the ISO (Boot Nitrux in full-debug mode) until the welcome wizard shows up, which is when the desktop is available.

I was only able to reduce the boot time to 40-41 seconds.

What I noticed is that the kernel takes approximately 13s to finish loading (according to systemd), so perhaps we can only load the necessary modules to the initramfs to reduce this boot time.

**Comment by UriHerrera** [comment]
I've changed the compression algorithm that is used to compress the ISO from xz to gzip, and the boot time decreases to 26.57 seconds. It also helps with Travis; it now takes about 17-19 minutes less to complete the job.

https://github.com/Nitrux/nitrux-iso-tool/blob/8d74bdd8e3936b8f15105aef06516bc8b02da4d2/build.sh#L80

Addendum:

The above is right for booting the ISO directly, i.e., in VirtualBox. When the user deploys the operating system, and there's no need to do things like setting up a new user folder, the boot time is actually of 19.66 seconds.

Compressing the initramfs with gzip instead of xz reduces the time it takes to boot the ISO directly to 22.28 seconds.

https://github.com/Nitrux/nitrux-iso-tool/blob/de1f169b7925bce9f4f7aeac7594cd968d00cce1/configs/files/initramfs.conf#L53

And having deployed the operating system, the boot time is of 17.84 seconds.

Still, it could be better.

------

Notes:
[Linux Kernel Fastboot On the Way](https://www.linuxplumbersconf.org/event/4/contributions/281/attachments/216/617/LPC_2019_kernel_fastboot_on_the_way.pdf)

- Perhaps we could somehow defer modules during the boot process? Like, loading only some modules from the initramfs and then have the rest of the kernel modules load after the graphical session has started.

- Disabling the on-demand CPU governor reduces the boot time to 14-15 seconds, although that's not beneficial for battery use and requires a reboot to use the performance governor.

- Tests performed using VirtualBox.

**Comment by lslvr** [comment]
Great, @UriHerrera!

**Comment by UriHerrera** [comment]
I am closing this in favor of the two referenced issues.
