### ISSUE TITLE
Generate locales

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/iso-tool#48]
Our current ISO suffers from a locale generation problem. We do include the translations for the software that we ship, but these are not available in System Settings.

Related https://github.com/Nitrux/nitrux-bug-tracker/issues/4

**Comment by UriHerrera** [comment]
Could this be a problem also introduced in changes done to https://github.com/Nitrux/tools?. @luis-lavaire

**Comment by lslvr** [comment]
@UriHerrera, what do you mean exactly? The `tools` don't have anything to do with locales. I'm not understanding your question. Could you give me a hint, please?

**Comment by UriHerrera** [comment]
> @UriHerrera, what do you mean exactly? The `tools` don't have anything to do with locales. I'm not understanding your question. Could you give me a hint, please?

See https://github.com/Nitrux/nitrux-bug-tracker/issues/4

This problem wasn't present before.

**Comment by lslvr** [comment]
I don't really think that the issue comes from there. `mkiso`, (which is the only tool that deals with the system) never modifies anything in `/etc`. So, I don't think that's the direction where we should look to.

**Comment by UriHerrera** [comment]
![VirtualBox_Ubuntu_02_06_2020_12_13_04](https://user-images.githubusercontent.com/3053525/83549162-7a465480-a4ca-11ea-9297-80d951ea1fc3.png)

Here's a screenshot of Nitrux 1.1.7, which was generated using this tool. This bug is _not_ present, as the list of available languages is available. So it's something that changed after this image was built.

![VirtualBox_Ubuntu_02_06_2020_12_16_06](https://user-images.githubusercontent.com/3053525/83549383-e032dc00-a4ca-11ea-9317-63a767aeba98.png)

Selecting a different language and logging out and back in __does change it__ and there are no partial translations.

This is the commit that generates it f609cfff268151065e75827f070c62b3b765fe9b

**Comment by UriHerrera** [comment]
![VirtualBox_Ubuntu_02_06_2020_12_54_56](https://user-images.githubusercontent.com/3053525/83555311-b631e780-a4d3-11ea-918e-f018c1b2077f.png)

![VirtualBox_Ubuntu_02_06_2020_12_55_07](https://user-images.githubusercontent.com/3053525/83555179-81259500-a4d3-11ea-97ef-35fc4e74d421.png)

Tested the Ubuntu image, it does not present this problem. 

This problem is specific to the Neon image and ours, meaning it's a KDE-specific problem or misconfiguration.

> I don't really think that the issue comes from there. `mkiso`, (which is the only tool that deals with the system) never modifies anything in `/etc`. So, I don't think that's the direction where we should look to.

You are correct. It's not the tools.

**Comment by UriHerrera** [comment]
Fixed in https://github.com/Nitrux/iso-tool/commit/957b862e299374a154f18fa53ac229cfafde276f

The problem was that `dpkg` excluded the translation files when installing packages, specifically to this issue from the `plasma-workspace` package.

Commenting on the offending line resolves the problem.

As is, it was a problem _introduced_ from upstream, not from our side.
