### ISSUE TITLE
nsswitch.conf is empty after exiting the chroot and before creating the ISO

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/iso-tool#51]
**Describe the bug**
ISOs have presented a bug where the use of `sudo` would show a message similar to `sudo unable to resolve address associated with hostname` meaning that the hostname wasn't being resolved by the system.

I have tracked this issue to the file `nsswitch.conf` being _empty_ after the chroot exits. However, the file is neither empty _before_ or during the chroot.

This issue was not present before and it might be related to new changes introduced in https://github.com/Nitrux/tools.

**Screenshots**
![VirtualBox_Nitrux_31_03_2020_18_07_20](https://user-images.githubusercontent.com/3053525/78086219-830b9480-737a-11ea-81e0-0e9c556a9a72.png)
> Error message after using sudo.

![VirtualBox_Nitrux_31_03_2020_18_09_27](https://user-images.githubusercontent.com/3053525/78086310-c9f98a00-737a-11ea-9c82-3100b297261d.png)
> The file is empty on the packaged ISO.

**Comment by lslvr** [comment]
It is —indeed— an issue in the tools repo. I just pushed a fix for it.

**Comment by lslvr** [comment]
@UriHerrera, can you confirm if the issue is still present?

**Comment by UriHerrera** [comment]
The problem is not present anymore. I'm closing this issue.
