### ISSUE TITLE
[Security] APT keys are not authenticated

### ISSUE THREAD

**Issue by TheAssassin** [Nitrux/iso-tool#6]
See https://github.com/Nitrux/mkiso/blob/master/build.sh#L50-L51.

Seems like the same issue persists across most build tools.

Related:
https://github.com/nomad-desktop/nxos-docker-image/issues/2
https://github.com/nomad-desktop/nx-software-center/issues/20

**Comment by lslvr** [comment]
Shouldn't those lines authenticate the packages?

**Comment by TheAssassin** [comment]
The problem is the key files are downloaded without any authentication. Manipulation is possible here, and it's fairly easy to secure this. See nomad-desktop/nxos-docker-image#4 for how to ensure the keys' authenticity (hardcoding a message digest (SHA 256 hash sum) of the file in the script, so when the key is downloaded, you can make sure it's the one you want to have by hashing the downloaded file and comparing the resulting hash sum to the one you expect).

*Actually, it's even possible to add the keys to this repository, and use the local files.*

**Comment by lslvr** [comment]
Great, @TheAssassin! Many thanks for the advice! :grin:

**Comment by lslvr** [comment]
I think that adding the keys to this repo would be the most secure way of working with the keys, but the problem I see with that method is that if files containing the keys change, they won't work when adding them with `apt-key`. I'm not sure if this is something to really worry about (I mean using local files) because I haven't worked too much with apt-based systems (only a couple years ago, when I started using Linux, and again since January of current year, due to my job with Nitrux).

**Comment by TheAssassin** [comment]
It's not very likely they will ever change. But if they did, any image you'd have built before would still contain them forever, using wget won't change that.

If you want to be able to notice changes, use wget with a hash, then when the hashs don't match, you'll notice as the build will fail.

**Comment by lslvr** [comment]
Oh, I see. Thanks for your help, @TheAssassin. The issue got solved on the fork I maintain on my account (I needed to use a Github token and don't have enough permissions in this repo, so I had to fork), and I will soon make a PR. Again, thanks a lot for your help! :grin:

**Comment by TheAssassin** [comment]
You're welcome. Feel free to mention me in the PR, I'll have a look then.

**Comment by lslvr** [comment]
Alright. :wink:

**Comment by lslvr** [comment]
Done. I pushed the changes directly, without merging the pull request. [Here](https://github.com/Nitrux/mkiso/blob/master/build.sh#L36) are the changes.
